Introduce DirectoryObject and FileObject in Workflow
pyiron/pyiron_contrib pull request #725
Opened 2023-06-19 17:08 UTC by samwaseda

This PR allows for working files which some softwares require.

- `FileObject` handles only the file and has no information of address i.e. it must be attached to a `DirectoryObject`
- The central path is known to `Workflow` -> a `Node` cannot create a directory if it is not attached to a `Workflow`
- The directory is created only if `workflow.working_directory` is called.
- Path: `workflow_name/function_name/file_name`

Example I:

```python
from pyiron_contrib.workflow import Workflow
from pyiron_contrib.workflow.node import Node

def f(x):
    return x

wf = Workflow("TEST")
n_f = Node(f, "f")
wf.add(n_f)
my_file = n_f.create_file('new_file')  # Creates all directories
my_file.write('something')

with open(my_file.path, 'r') as f:
    print(f.read())

wf.working_directory.delete()  # deletes everything
```

Output:

```
TEST/f/new_file
something
```

Example II

```python
def f(x):
    return x

n_f = Node(f, "f")
my_file = n_f.create_file('new_file')  # Error, because not attached to a workflow
```

Closes #702

2023-06-19 18:04 UTC, liamhuber requested changes
lgtm. One UX question.

Needs tests though. `files.py` is super readable and I don't see anything that could go wrong, but tests should be there at least for the coverage 😉 For the workflow and nodes I actually see tests being useful as they lock-in two promises:
- Paths are based off labels (this is actually mis-spoken in the PR comment, it uses the node label not the function name -- these are the same by default but can change, and even do change in your example!)
- Nodes not being able to create a file if not in a workflow (maybe we want to change that spec later, but for now I like it)

At first I thought it might be overkill to put `create_file` right on `Node` (as it wouldn't be accessible to any node that doesn't define `self` in the function argument), but actually (a) I don't mind the extra code that much, and (b) maybe we can exploit it when it comes time to serialize IO. So I want to keep in the back of our minds the idea of refactoring these methods away to some more specific child class, but for now it seems perfectly appropriate to have it here.

2023-06-20 07:40 UTC, samwaseda commented
> Needs tests though.

Ah yes, I left a comment in the [botched previous PR](https://github.com/pyiron/pyiron_contrib/pull/722) saying I was waiting for the first comments but I forgot to write the same in this PR.


> * Paths are based off labels (this is actually mis-spoken in the PR comment, it uses the node label not the function name -- these are the same by default but can change, and even do change in your example!)

Yeah it's good that we talk about it, because until I saw [this PR](https://github.com/pyiron/pyiron_contrib/pull/727) I didn't really think that the label can be different.

> * Nodes not being able to create a file if not in a workflow (maybe we want to change that spec later, but for now I like it)
> 
> At first I thought it might be overkill to put `create_file` right on `Node` (as it wouldn't be accessible to any node that doesn't define `self` in the function argument), but actually (a) I don't mind the extra code that much, and (b) maybe we can exploit it when it comes time to serialize IO. So I want to keep in the back of our minds the idea of refactoring these methods away to some more specific child class, but for now it seems perfectly appropriate to have it here.

I also thought about defining it in `node.working_directory.create_file`, and to be honest I don't have a very strong feeling, so I can also move it there.

2023-06-20 07:40 UTC, samwaseda commented on pyiron_contrib/workflow/files.py
> +    def __init__(self, file_name: str, directory: DirectoryObject):
yeah that might be a good idea

2023-06-20 07:47 UTC, samwaseda commented on pyiron_contrib/workflow/files.py
> +    def __init__(self, file_name: str, directory: DirectoryObject):
although I was thinking about using the same object for reading as well, i.e. for all files which are created during `run` should also be accessed with this object, so I'm gonna put the warning in `write`.

2023-06-20 18:29 UTC, samwaseda commented
> A simple example is a Murnaghan node, where several atomistic jobs (with each a separate working directory) need to be created. Thus, nodes should be able to create subdirectories with the working directory of the workflow being the parent directory.

There, I think there's a bit of a difference in terminology with respect to the current implementation of `Workflow`: a `Node` is the smallest unit that wraps **one** function, while a `Workflow` can contain multiple nodes and itself can act like a node. This means, in the example of Murnaghan (which is a bit difficult to talk about, because parallel jobs are not fully conceptualised on our side), each of the atomistic job is a `Node`, but the Murnaghan job itself is a `Workflow`. So I think it would be sufficient to have one directory for one node.

This being said, there indeed should be a functionality that allows a workflow folder within a parent workflow. I just didn't do it because I didn't see a possibility in the current implementation how to see whether a workflow is attached to a parent workflow (i.e. I don't know if it's possible for a child workflow to know whether it has a parent workflow).

Comments from @liamhuber might be appreciated here.

2023-06-20 18:52 UTC, liamhuber commented
> but the Murnaghan job itself is a `Workflow`

No, Joerg is correct; you can in principle have a node that executes the entire Murnaghan procedure. It doesn't even need to make sub-nodes out of the steps! The idea that nodes are functional and idempotent is a "best practice" and not strictly enforced, and even here you could have a node that starts a pyiron project, makes a bunch of lammps jobs, runs everything, scrapes the results, and finishes that _is_ both idempotent and functional! Of course, you also could make a `Murnaghan` workflow where each calculation is a node, and then you don't need this.

A `task` is just a computational unit and a `Node.run()` might generate multiple of them at once. There's no reason to forbid a task from having its own working directory. This is already possible from inside the node of course, you can use `self.working_directory` as a root and then make new sub-dirs as part of the task. I don't have any objection to adding tools that make this subdirectory creation easier.

2023-06-21 07:35 UTC, samwaseda commented
Ok then it doesn't sound like something systematic, so I propose the following solution (which is only marginally different from the current implementation):

```python
def my_function(x):
    return x

wf = Workflow("TEST")
n_f = Node(my_function, "output")
wf.add(n_f)
node_file = n_f.working_directory.create_file('node_directory_file')
node_file.write('This one is written in `my_function` and is inside the node directory')
sub_directory = n_f.working_directory.create_subdirectory("node_subdirectory")
node_sub_file = sub_directory.create_file('node_subdirectory_file')
node_sub_file.write('This one is written in `node_subdirectory` and is inside the node subdirectory')
```

```python
print(n_f.working_directory.list_content())
```

Output:

```python
{'dir': ['TEST/my_function/node_subdirectory'],
 'file': ['TEST/my_function/node_directory_file'],
 'mount': [],
 'symlink': [],
 'block_device': [],
 'char_device': [],
 'fifo': [],
 'socket': []}
```

```python
print(node_file.path)
```

Output:

```python
TEST/my_function/node_directory_file
```

```python
print(sub_directory.list_content())
```

Output:

```python
{'dir': [],
 'file': ['TEST/my_function/node_subdirectory/node_subdirectory_file'],
 'mount': [],
 'symlink': [],
 'block_device': [],
 'char_device': [],
 'fifo': [],
 'socket': []}
```

```python
print(node_sub_file.path)
```

Output:

```python
TEST/my_function/node_subdirectory/node_subdirectory_file
```

One thing that changes here is that `create_file` is not part of `Node` anymore, which comes back to the point that @liamhuber had made. Would this be acceptable?

2023-06-21 15:53 UTC, liamhuber reviewed
A minor question and a readability nit, but otherwise lgtm now.

Regarding the larger question brought up by Joerg, I think the current implementation where neither workflow nor node have special creation routines but _need_ to go via their `working_directory` is a good solution -- all the capability is available, and we're not biasing towards one particular usage style.

2023-06-22 13:42 UTC, samwaseda commented on pyiron_contrib/workflow/files.py
> +            warnings.warn(f"{self.file_name} already exists")
I changed the default mode.

2023-06-22 15:51 UTC, liamhuber reviewed
Nice. A couple minor suggestions for extending the tests, but otherwise lgtm

2023-06-22 15:51 UTC, liamhuber commented on tests/unit/workflow/test_workflow.py
> +
```suggestion
self.assertIsInstance(wf.working_directory, DirectoryObject)
self.assertTrue(wf.working_directory.path.absolute().endswith(wf.label)

```

Maybe the endswith needs a "/" or something? Also I guess we need similar tests for `Node`, where it starts as none, raises an error when asked for, and then passes the same endswith test after a parent is added

2023-06-26 21:08 UTC, liamhuber commented
I could have sworn GitHub used to rebase stacked PRs onto main _automatically_ when their target got merged and deleted....

2023-06-26 22:20 UTC, liamhuber commented
Test failures on `` look like they're just typical windows stuff, although the `is_mount` thing is new to me:

```
======================================================================
ERROR: test_write (workflow.test_files.TestFiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\pyiron_contrib\pyiron_contrib\tests\unit\workflow\test_files.py", line 21, in test_write
    self.assertTrue("test/test.txt" in self.directory.list_content()['file'])
  File "D:\a\pyiron_contrib\pyiron_contrib\pyiron_contrib\workflow\files.py", line 48, in list_content
    return categorize_folder_items(self.path)
  File "D:\a\pyiron_contrib\pyiron_contrib\pyiron_contrib\workflow\files.py", line 31, in categorize_folder_items
    if getattr(item, f"is_{tt}")():
  File "C:\Miniconda3\envs\my-env\lib\pathlib.py", line 1461, in is_mount
    raise NotImplementedError("Path.is_mount() is unsupported on this system")
NotImplementedError: Path.is_mount() is unsupported on this system

======================================================================
FAIL: test_path (workflow.test_files.TestFiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\pyiron_contrib\pyiron_contrib\tests\unit\workflow\test_files.py", line 30, in test_path
    self.assertEqual(str(f.path), "test/test.txt")
AssertionError: 'test\\test.txt' != 'test/test.txt'
- test\test.txt
?     ^
+ test/test.txt
?     ^


----------------------------------------------------------------------
```

2023-06-26 22:21 UTC, liamhuber reviewed
It would be nice to extend the tests as [here](https://github.com/pyiron/pyiron_contrib/pull/725/files#r1238726659), but otherwise once the tests are passing this is looking alright to me.

2023-06-27 08:25 UTC, samwaseda commented
> Test failures on `` look like they're just typical windows stuff, although the `is_mount` thing is new to me

I was unnecessarily calling all functions starting with `is`. Now it should be fine.

2023-06-27 14:27 UTC, liamhuber approved these changes
Super.

I think there is a way to more elegantly convert `"test/tests"` to look like a path from the current system than to convert all the references to "/", but what you do here is clear and effective so it's also ok with me.

2023-06-27 14:29 UTC, merged